env:
  - CGO_ENABLED=0

builds:
  - main: ./cmd
    ldflags:
      - -s
      - -w
      - -X main.version={{ .Version }}
    targets:
      - linux_amd64
      - linux_arm64

archives:
  - id: zip
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

dockers:
  - dockerfile: Dockerfile.goreleaser
    goarch: amd64
    goos: linux
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
    image_templates:
      - "flashbots/eth-faucet-backend:{{ .Tag }}-amd64"
      - "ghcr.io/flashbots/eth-faucet-backend:{{ .Tag }}-amd64"

  - dockerfile: Dockerfile.goreleaser
    goarch: arm64
    goos: linux
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
    image_templates:
      - "flashbots/eth-faucet-backend:{{ .Tag }}-arm64"
      - "ghcr.io/flashbots/eth-faucet-backend:{{ .Tag }}-arm64"

docker_manifests:
  - name_template: "flashbots/eth-faucet-backend:{{ .Tag }}"
    image_templates:
      - "flashbots/eth-faucet-backend:{{ .Tag }}-amd64"
      - "flashbots/eth-faucet-backend:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/flashbots/eth-faucet-backend:{{ .Tag }}"
    image_templates:
      - "ghcr.io/flashbots/eth-faucet-backend:{{ .Tag }}-amd64"
      - "ghcr.io/flashbots/eth-faucet-backend:{{ .Tag }}-arm64"
